// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC_EN.Models
{
  public partial class City
  {
    public City()
    {
      PartnerResidenceCities = new HashSet<Partner>();
      PartnerShipmentCities = new HashSet<Partner>();
    }

    public int CityId { get; set; }
    [Display(Name = "Country")] public string CountryCode { get; set; }
    [Display(Name = "City Name")] public string CityName { get; set; }
    [Display(Name = "Postal Code")] public int PostalCode { get; set; }
    [Display(Name = "Postal Name")] public string PostalName { get; set; }

    public virtual Country CountryCodeNavigation { get; set; }
    public virtual ICollection<Partner> PartnerResidenceCities { get; set; }
    public virtual ICollection<Partner> PartnerShipmentCities { get; set; }
  }
}