// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MVC_EN.Models;

public partial class Country
{
  [DisplayName("Country Code"), Required, MaxLength(3)]
  public string CountryCode { get; set; } = null!;

  [DisplayName("Country Name"), Required]
  public string CountryName { get; set; } = null!;

  [DisplayName("ISO3"), MaxLength(3)]
  public string? CountryIso3 { get; set; }

  public virtual ICollection<City> Cities { get; set; } = new List<City>();
}