// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace MVC_EN.Models
{
  public partial class Country
  {
    public Country()
    {
      Cities = new HashSet<City>();
    }

    [DisplayName("Country Code")]
    public string CountryCode { get; set; }
    [DisplayName("Country Name")]
    public string CountryName { get; set; }
    [DisplayName("ISO3")]
    public string CountryIso3 { get; set; }

    public virtual ICollection<City> Cities { get; set; }
  }
}