// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;

namespace MVC_EN.Models;

public partial class Country
{
  [Display(Name = "Country Code", Prompt = "Enter country code"), Required, MaxLength(3)]
  public string CountryCode { get; set; } = null!;

  [Display(Name = "Country Name"), Required]
  public string CountryName { get; set; } = null!;

  [Display(Name = "ISO3"), MaxLength(3)]
  public string? CountryIso3 { get; set; }

  public virtual ICollection<City> Cities { get; set; } = new List<City>();
}