// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using MVC_EN.Controllers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC_EN.Models
{
  public partial class Product
  {
    public Product()
    {
      Items = new HashSet<Item>();
    }

    [Remote(action: nameof(ProductsController.CheckProductNumber), controller: "Products", ErrorMessage = "A product with the same number already exists.")]
    [Required, Display(Name = "Product Number")]
    public int ProductNumber { get; set; }
    [Required, Display(Name = "Product Name")] public string ProductName { get; set; }
    [Display(Name = "Unit Name")] public string UnitName { get; set; }
    
    [Range(0, double.MaxValue, ErrorMessage = "Price must be non-negative number")] 
    [Required, Display(Name = "Price")] public decimal Price { get; set; }
    [Display(Name = "Is service?")] public bool IsService { get; set; }
    public string Description { get; set; }
    public byte[] Photo { get; set; }
    public int? PhotoChecksum { get; set; }

    public virtual ICollection<Item> Items { get; set; }
  }
}