// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModel
{
    public partial class Drzava
    {
        public Drzava()
        {
            Mjesto = new HashSet<Mjesto>();
        }

        /// <summary>
        /// Oznaka države
        /// </summary>
        public string OznDrzave { get; set; }
        /// <summary>
        /// Naziv države
        /// </summary>
        public string NazDrzave { get; set; }
        public string Iso3drzave { get; set; }
        public int? SifDrzave { get; set; }

        public virtual ICollection<Mjesto> Mjesto { get; set; }
    }
}