// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModel
{
    public partial class Partner
    {
        public Partner()
        {
            Dokument = new HashSet<Dokument>();
        }

        /// <summary>
        /// Identifikator partnera
        /// </summary>
        public int IdPartnera { get; set; }
        /// <summary>
        /// Tip partnera (F-fizička, P-pravna)
        /// </summary>
        public string TipPartnera { get; set; }
        public string Oib { get; set; }
        /// <summary>
        /// Identifikator mjesta partnera
        /// </summary>
        public int? IdMjestaPartnera { get; set; }
        /// <summary>
        /// Adresa partnera
        /// </summary>
        public string AdrPartnera { get; set; }
        /// <summary>
        /// Identifikator mjesta isporuke
        /// </summary>
        public int? IdMjestaIsporuke { get; set; }
        /// <summary>
        /// Adresa isporuke
        /// </summary>
        public string AdrIsporuke { get; set; }

        public virtual Mjesto IdMjestaIsporukeNavigation { get; set; }
        public virtual Mjesto IdMjestaPartneraNavigation { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual Tvrtka Tvrtka { get; set; }
        public virtual ICollection<Dokument> Dokument { get; set; }
    }
}