// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using MVC.Controllers;

namespace MVC.Models;

public partial class Artikl
{
  /// <summary>
  /// Šifra artikla
  /// </summary>
  [Required(ErrorMessage = "Potrebno je uniijeti šifru artikla")]
  [Remote(action: nameof(ArtiklController.ProvjeriSifruArtikla), controller: "Artikl", ErrorMessage = "Artikl s navedenom šifrom već postoji")]
  [Display(Name = "Šifra artikla")] 
  public int SifArtikla { get; set; }

  /// <summary>
  /// Naziv artikla
  /// </summary>
  [Required(ErrorMessage = "Potrebno je uniijeti naziv artikla")]
  [Display(Name = "Naziv artikla")] 
  public string NazArtikla { get; set; } = null!;

  /// <summary>
  /// Jedinica mjere
  /// </summary>
  [Display(Name = "Jedinica mjere")] 
  public string JedMjere { get; set; } = null!;

  /// <summary>
  /// Cijena artikla
  /// </summary>
  [Required(ErrorMessage = "Potrebno je uniijeti cijenu artikla")]
  [Range(0, double.MaxValue, ErrorMessage = "Cijena artikla mora biti nenegativan broj")]
  [Display(Name = "Cijena artikla")] 
  public decimal CijArtikla { get; set; }

  /// <summary>
  /// Check box, usluge nemaju sliku
  /// </summary>
  [Display(Name = "Usluga?")] 
  public bool ZastUsluga { get; set; }
  [Display(Name = "Tekst/Opis")]
  public string? TekstArtikla { get; set; }
  [Display(Name = "Slika")]
  public byte[]? SlikaArtikla { get; set; }

    public int? SlikaChecksum { get; set; }

    public virtual ICollection<Stavka> Stavka { get; set; } = new List<Stavka>();
}