// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// Data annotations attributes are added later manually.
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models;

public partial class Drzava
{
  /// <summary>
  /// Oznaka države
  /// </summary>
  [Display(Name = "Oznaka države"), Required, MaxLength(3)]
  public string OznDrzave { get; set; } = null!;

  /// <summary>
  /// Naziv države
  /// </summary>
  [Display(Name = "Naziv države", Prompt = "Unesite naziv"), Required]
  public string NazDrzave { get; set; } = null!;

  [Display(Name = "ISO3 oznaka"), MaxLength(3)]
  public string? Iso3drzave { get; set; }

  [Display(Name = "Šifra države")]
  public int? SifDrzave { get; set; }

  public virtual ICollection<Mjesto> Mjesto { get; set; } = new List<Mjesto>();
}