// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace MVC.Models;

public partial class Mjesto
{
  /// <summary>
  /// Identifikator mjesta
  /// </summary>
  public int IdMjesta { get; set; }

  /// <summary>
  /// Oznaka države
  /// </summary>
  [Display(Name = "Država")]
  public string OznDrzave { get; set; } = null!;

  /// <summary>
  /// Naziv mjesta
  /// </summary>
  [Display(Name = "Naziv mjesta")]
  public string NazMjesta { get; set; } = null!;

  /// <summary>
  /// Poštanski broj mjesta
  /// </summary>
  [Display(Name = "Poštanski broj mjesta")]
  public int PostBrMjesta { get; set; }

  /// <summary>
  /// Naziv dostavne pošte
  /// </summary>
  [Display(Name = "Poštanski naziv mjesta")]
  public string? PostNazMjesta { get; set; }

  [ValidateNever] public virtual Drzava OznDrzaveNavigation { get; set; } = null!;

  public virtual ICollection<Partner> PartnerIdMjestaIsporukeNavigation { get; set; } = new List<Partner>();

  public virtual ICollection<Partner> PartnerIdMjestaPartneraNavigation { get; set; } = new List<Partner>();
}