// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MVC.Models;

public partial class Tvrtka
{
    /// <summary>
    /// Identifikator tvrtke
    /// </summary>
    public int IdTvrtke { get; set; }

    /// <summary>
    /// Matični broj tvrtke
    /// </summary>
    public string MatBrTvrtke { get; set; } = null!;

    /// <summary>
    /// Naziv tvrtke
    /// </summary>
    public string NazivTvrtke { get; set; } = null!;

    public virtual Partner IdTvrtkeNavigation { get; set; } = null!;
}