// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EF.Model;

public partial class FirmaContext : DbContext
{
    public FirmaContext(DbContextOptions<FirmaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Artikl> Artikl { get; set; }

    public virtual DbSet<Dokument> Dokument { get; set; }

    public virtual DbSet<Drzava> Drzava { get; set; }

    public virtual DbSet<Mjesto> Mjesto { get; set; }

    public virtual DbSet<Osoba> Osoba { get; set; }

    public virtual DbSet<Partner> Partner { get; set; }

    public virtual DbSet<Stavka> Stavka { get; set; }

    public virtual DbSet<Tvrtka> Tvrtka { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Artikl>(entity =>
        {
            entity.HasKey(e => e.SifArtikla)
                .HasName("pk_Artikl")
                .IsClustered(false);

            entity.Property(e => e.SifArtikla)
                .HasComment("Šifra artikla")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Artikl_SifArtikla");
            entity.Property(e => e.CijArtikla)
                .HasComment("Cijena artikla")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Artikl_CijArtikla")
                .HasColumnType("money");
            entity.Property(e => e.JedMjere)
                .HasMaxLength(5)
                .HasDefaultValue("kom")
                .HasComment("Jedinica mjere")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Artikl_JedMjere");
            entity.Property(e => e.NazArtikla)
                .HasMaxLength(255)
                .HasComment("Naziv artikla");
            entity.Property(e => e.SlikaChecksum).HasComputedColumnSql("(checksum([SlikaArtikla]))", false);
            entity.Property(e => e.ZastUsluga)
                .HasComment("Check box, usluge nemaju sliku")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Artikl_ZastUsluga");
        });

        modelBuilder.Entity<Dokument>(entity =>
        {
            entity.HasKey(e => e.IdDokumenta)
                .HasName("pk_Dokument")
                .IsClustered(false);

            entity.Property(e => e.IdDokumenta).HasComment("Identifikator dokumenta");
            entity.Property(e => e.BrDokumenta)
                .HasComment("Broj dokumenta")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Dokument_BrDokumenta");
            entity.Property(e => e.DatDokumenta)
                .HasComment("Datum dokumenta")
                .HasColumnType("datetime");
            entity.Property(e => e.IdPartnera).HasComment("Partner");
            entity.Property(e => e.IdPrethDokumenta).HasComment("Prethodni dokument");
            entity.Property(e => e.IznosDokumenta)
                .HasComment("Ukupno stavke s porezom")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Dokument__IznosDokumenta")
                .HasColumnType("money");
            entity.Property(e => e.PostoPorez)
                .HasComment("Postotak poreza")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Dokument__PostoPorez")
                .HasColumnType("decimal(4, 2)");
            entity.Property(e => e.VrDokumenta)
                .HasMaxLength(20)
                .HasComment("Vrsta dokumenta");

            entity.HasOne(d => d.IdPartneraNavigation).WithMany(p => p.Dokument)
                .HasForeignKey(d => d.IdPartnera)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Partner_Dokument");

            entity.HasOne(d => d.IdPrethDokumentaNavigation).WithMany(p => p.InverseIdPrethDokumentaNavigation)
                .HasForeignKey(d => d.IdPrethDokumenta)
                .HasConstraintName("fk_Dokument_Dokument");
        });

        modelBuilder.Entity<Drzava>(entity =>
        {
            entity.HasKey(e => e.OznDrzave)
                .HasName("pk_Drzava")
                .IsClustered(false);

            entity.HasIndex(e => e.NazDrzave, "UIX_Drzava_NazDrzave").IsUnique();

            entity.Property(e => e.OznDrzave)
                .HasMaxLength(3)
                .HasComment("Oznaka države");
            entity.Property(e => e.Iso3drzave)
                .HasMaxLength(3)
                .HasColumnName("ISO3Drzave");
            entity.Property(e => e.NazDrzave)
                .HasMaxLength(255)
                .HasComment("Naziv države");
            entity.Property(e => e.SifDrzave)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "df_Drzava_SifDrzave");
        });

        modelBuilder.Entity<Mjesto>(entity =>
        {
            entity.HasKey(e => e.IdMjesta)
                .HasName("pk_Mjesto")
                .IsClustered(false);

            entity.Property(e => e.IdMjesta).HasComment("Identifikator mjesta");
            entity.Property(e => e.NazMjesta)
                .HasMaxLength(40)
                .HasComment("Naziv mjesta");
            entity.Property(e => e.OznDrzave)
                .HasMaxLength(3)
                .HasComment("Oznaka države");
            entity.Property(e => e.PostBrMjesta).HasComment("Poštanski broj mjesta");
            entity.Property(e => e.PostNazMjesta)
                .HasMaxLength(50)
                .HasComment("Naziv dostavne pošte");

            entity.HasOne(d => d.OznDrzaveNavigation).WithMany(p => p.Mjesto)
                .HasForeignKey(d => d.OznDrzave)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Drzava_Mjesto");
        });

        modelBuilder.Entity<Osoba>(entity =>
        {
            entity.HasKey(e => e.IdOsobe)
                .HasName("pk_Osoba")
                .IsClustered(false);

            entity.Property(e => e.IdOsobe)
                .ValueGeneratedNever()
                .HasComment("Identifikator osobe");
            entity.Property(e => e.ImeOsobe)
                .HasMaxLength(20)
                .HasComment("Ime osobe");
            entity.Property(e => e.PrezimeOsobe)
                .HasMaxLength(20)
                .HasComment("Prezime osobe");

            entity.HasOne(d => d.IdOsobeNavigation).WithOne(p => p.Osoba)
                .HasForeignKey<Osoba>(d => d.IdOsobe)
                .HasConstraintName("fk_Partner_Osoba");
        });

        modelBuilder.Entity<Partner>(entity =>
        {
            entity.HasKey(e => e.IdPartnera)
                .HasName("pk_Partner")
                .IsClustered(false);

            entity.HasIndex(e => e.Oib, "UIX_Partner_OIB").IsUnique();

            entity.Property(e => e.IdPartnera).HasComment("Identifikator partnera");
            entity.Property(e => e.AdrIsporuke)
                .HasMaxLength(50)
                .HasComment("Adresa isporuke");
            entity.Property(e => e.AdrPartnera)
                .HasMaxLength(50)
                .HasComment("Adresa partnera");
            entity.Property(e => e.IdMjestaIsporuke).HasComment("Identifikator mjesta isporuke");
            entity.Property(e => e.IdMjestaPartnera).HasComment("Identifikator mjesta partnera");
            entity.Property(e => e.Oib)
                .HasMaxLength(50)
                .HasColumnName("OIB");
            entity.Property(e => e.TipPartnera)
                .HasMaxLength(1)
                .HasComment("Tip partnera (F-fizička, P-pravna)");

            entity.HasOne(d => d.IdMjestaIsporukeNavigation).WithMany(p => p.PartnerIdMjestaIsporukeNavigation)
                .HasForeignKey(d => d.IdMjestaIsporuke)
                .HasConstraintName("fk_Mjesto_Partner_Isporuka");

            entity.HasOne(d => d.IdMjestaPartneraNavigation).WithMany(p => p.PartnerIdMjestaPartneraNavigation)
                .HasForeignKey(d => d.IdMjestaPartnera)
                .HasConstraintName("fk_Mjesto_Partner_Sjediste");
        });

        modelBuilder.Entity<Stavka>(entity =>
        {
            entity.HasKey(e => e.IdStavke)
                .HasName("pk_Stavka")
                .IsClustered(false);

            entity.HasIndex(e => new { e.IdDokumenta, e.SifArtikla }, "UIX_Stavka_IdDokumenta_SifArtikla").IsUnique();

            entity.Property(e => e.IdDokumenta).HasComment("Identifikator dokumenta");
            entity.Property(e => e.JedCijArtikla)
                .HasComment("Cijena jediničnog artikla bez poreza. Inicijalno cijena iz tablice Artikl")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Stavka_JedCijArtikla")
                .HasColumnType("money");
            entity.Property(e => e.KolArtikla)
                .HasComment("Količina artikla (za pojedine jedinice mjere može biti decimalni broj)")
                .HasColumnType("decimal(18, 5)");
            entity.Property(e => e.PostoRabat)
                .HasComment("Postotak popusta za pojedinu stavku")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Stavka_PostoRabat")
                .HasColumnType("decimal(4, 2)");
            entity.Property(e => e.SifArtikla)
                .HasComment("Šifra artikla")
                .HasAnnotation("Relational:DefaultConstraintName", "df_Stavka_SifArtikla");

            entity.HasOne(d => d.IdDokumentaNavigation).WithMany(p => p.Stavka)
                .HasForeignKey(d => d.IdDokumenta)
                .HasConstraintName("fk_Dokument_Stavka");

            entity.HasOne(d => d.SifArtiklaNavigation).WithMany(p => p.Stavka)
                .HasForeignKey(d => d.SifArtikla)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Artikl_Stavka");
        });

        modelBuilder.Entity<Tvrtka>(entity =>
        {
            entity.HasKey(e => e.IdTvrtke)
                .HasName("pk_Tvrtka")
                .IsClustered(false);

            entity.HasIndex(e => e.MatBrTvrtke, "UIX_Tvrtka_MatBrTvrtke").IsUnique();

            entity.Property(e => e.IdTvrtke)
                .ValueGeneratedNever()
                .HasComment("Identifikator tvrtke");
            entity.Property(e => e.MatBrTvrtke)
                .HasMaxLength(30)
                .HasComment("Matični broj tvrtke");
            entity.Property(e => e.NazivTvrtke)
                .HasMaxLength(50)
                .HasComment("Naziv tvrtke");

            entity.HasOne(d => d.IdTvrtkeNavigation).WithOne(p => p.Tvrtka)
                .HasForeignKey<Tvrtka>(d => d.IdTvrtke)
                .HasConstraintName("fk_Partner_Tvrtka");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}