// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EF.Model;

public partial class Mjesto
{
    /// <summary>
    /// Identifikator mjesta
    /// </summary>
    public int IdMjesta { get; set; }

    /// <summary>
    /// Oznaka države
    /// </summary>
    public string OznDrzave { get; set; } = null!;

    /// <summary>
    /// Naziv mjesta
    /// </summary>
    public string NazMjesta { get; set; } = null!;

    /// <summary>
    /// Poštanski broj mjesta
    /// </summary>
    public int PostBrMjesta { get; set; }

    /// <summary>
    /// Naziv dostavne pošte
    /// </summary>
    public string? PostNazMjesta { get; set; }

    public virtual Drzava OznDrzaveNavigation { get; set; } = null!;

    public virtual ICollection<Partner> PartnerIdMjestaIsporukeNavigation { get; set; } = new List<Partner>();

    public virtual ICollection<Partner> PartnerIdMjestaPartneraNavigation { get; set; } = new List<Partner>();
}