// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EFModel;

public partial class Item
{
    public int ItemId { get; set; }

    public int DocumentId { get; set; }

    public int ProductNumber { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal Discount { get; set; }

    public virtual Document Document { get; set; } = null!;

    public virtual Product ProductNumberNavigation { get; set; } = null!;
}