// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Osoba
{
    /// <summary>
    /// Identifikator osobe
    /// </summary>
    public int IdOsobe { get; set; }

    /// <summary>
    /// Prezime osobe
    /// </summary>
    public string PrezimeOsobe { get; set; } = null!;

    /// <summary>
    /// Ime osobe
    /// </summary>
    public string ImeOsobe { get; set; } = null!;

    public virtual Partner IdOsobeNavigation { get; set; } = null!;
}