// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EF_EN.Model;

public partial class Company
{
    public int CompanyId { get; set; }

    public string RegistrationNumber { get; set; } = null!;

    public string CompanyName { get; set; } = null!;

    public virtual Partner CompanyNavigation { get; set; } = null!;
}