// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EF_EN.Model;

public partial class Document
{
    public int DocumentId { get; set; }

    public string DocumentType { get; set; } = null!;

    public int DocumentNo { get; set; }

    public DateTime DocumentDate { get; set; }

    public int PartnerId { get; set; }

    public int? PreviousDocumentId { get; set; }

    public decimal Vat { get; set; }

    public decimal Amount { get; set; }

    public virtual ICollection<Document> InversePreviousDocument { get; set; } = new List<Document>();

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual Partner Partner { get; set; } = null!;

    public virtual Document? PreviousDocument { get; set; }
}